INSERT INTO posts (title, content, category, status)
VALUES
    ('Cara Meningkatkan Performa Web Service', 'Artikel ini membahas beberapa teknik caching, load balancing, serta optimasi query database untuk meningkatkan performa layanan berbasis web.', 'Technology', 'Published'),
    ('Tips Belajar Golang untuk Pemula', 'Belajar Golang tidak sesulit yang dibayangkan. Mulailah dari variabel, fungsi, concurrency, serta praktik membuat REST API sederhana.', 'Programming', 'Published'),
    ('Resep Ayam Geprek Pedas Level 10', 'Menu ayam geprek kini banyak disukai. Resep ini menjelaskan cara membuat sambal bawang pedas serta trik agar ayam tetap crispy.', 'Food', 'Draft'),
    ('Cara Menabung Untuk Anak Muda', 'Banyak anak muda kesulitan mengatur keuangan. Artikel ini memberikan contoh pembagian dana 50-30-20 dan tips konsisten menabung.', 'Lifestyle', 'Published'),
    ('5 Tempat Wisata Tersembunyi di Bali', 'Selain pantai terkenal, Bali memiliki wisata tersembunyi yang belum banyak diketahui. Cocok untuk liburan tenang dan instagramable.', 'Travel', 'Published'),
    ('Rakit PC Gaming Budget 5 Jutaan', 'Panduan memilih prosesor, VGA, RAM, serta power supply terbaik untuk merakit PC gaming murah namun tetap bertenaga.', 'Technology', 'Draft'),
    ('Pentingnya Unit Testing dalam Software Development', 'Unit testing membantu mencegah bug sebelum masuk ke production. Artikel ini menjelaskan manfaat dan contoh implementasinya.', 'Programming', 'Published'),
    ('Cara Mengatur Pola Tidur yang Baik', 'Kurang tidur mempengaruhi kesehatan. Tips ini membantu memperbaiki kualitas tidur dengan rutinitas yang benar.', 'Lifestyle', 'Published'),
    ('Kuliner Malam Terbaik di Bandung', 'Bandung memiliki banyak pilihan makanan malam. Mulai dari sate, martabak, hingga roti bakar legendaris.', 'Food', 'Published'),
    ('Panduan Belanja Online Aman', 'Belanja online bisa berisiko jika tidak hati-hati. Gunakan marketplace terpercaya dan cek review sebelum membeli.', 'Lifestyle', 'Published'),
    ('Perkembangan AI di Indonesia', 'AI semakin berkembang di berbagai sektor seperti kesehatan, fintech, hingga transportasi. Banyak startup mulai menerapkan machine learning.', 'Technology', 'Published'),
    ('Belajar Dasar Docker dan Container', 'Docker memudahkan proses deployment. Artikel ini menjelaskan konsep container, image, dan cara menjalankan aplikasi.', 'Programming', 'Draft'),
    ('Cara Mengurangi Kecanduan Smartphone', 'Terlalu sering bermain HP berdampak buruk. Tips ini membantu mengurangi penggunaan berlebihan dengan jadwal digital detox.', 'Lifestyle', 'Published'),
    ('Resep Nasi Goreng Rumahan', 'Nasi goreng sederhana namun enak, lengkap dengan bumbu halus dan topping ayam suwir.', 'Food', 'Published'),
    ('Perbedaan React dan Vue', 'Banyak developer bingung memilih framework. Artikel ini menjelaskan perbedaan fitur, performa, dan kendala masing-masing.', 'Technology', 'Published'),
    ('5 Laptop Terbaik untuk Programmer', 'Rekomendasi laptop dengan performa tinggi, RAM besar, dan layar nyaman untuk ngoding.', 'Technology', 'Draft'),
    ('Strategi Social Media Marketing', 'Bisnis online perlu strategi digital marketing yang tepat agar konten bisa menjangkau lebih banyak audience.', 'Business', 'Published'),
    ('Cara Membuat Portfolio Online', 'Portfolio membantu meningkatkan peluang kerja. Gunakan GitHub, personal website, dan contoh proyek nyata.', 'Career', 'Published'),
    ('Serunya Solo Traveling ke Jepang', 'Banyak tempat menarik di Jepang untuk solo traveler, mulai dari kuil, taman, hingga street food.', 'Travel', 'Published'),
    ('Paket Internet Harian Termurah', 'Perbandingan paket internet harian dari beberapa provider besar di Indonesia.', 'Technology', 'Published'),
    ('Kapan Waktu Terbaik Olahraga?', 'Olahraga dapat dilakukan kapan saja, namun penelitian menunjukkan pagi hari memiliki banyak manfaat kesehatan.', 'Lifestyle', 'Draft'),
    ('Belajar REST API dan JSON', 'REST API adalah standar komunikasi client-server modern. Artikel ini menjelaskan request, response, dan contoh endpoint.', 'Programming', 'Published'),
    ('Menu Sarapan Praktis di Pagi Hari', 'Beberapa rekomendasi sarapan simpel seperti roti bakar, oatmeal, atau telur orak-arik.', 'Food', 'Published'),
    ('Pengalaman Naik Kereta Malam', 'Bepergian dengan kereta malam memiliki sensasi berbeda. Cocok untuk perjalanan jauh agar tidak membuang waktu siang.', 'Travel', 'Published'),
    ('Perbedaan SSD dan HDD', 'SSD lebih cepat dan tahan guncangan, sedangkan HDD memiliki kapasitas besar dengan harga lebih murah.', 'Technology', 'Published'),
    ('Tips Mengatur Waktu Kuliah dan Kerja', 'Banyak mahasiswa bekerja sambilan. Artikel ini membahas manajemen waktu agar keduanya tetap produktif.', 'Career', 'Published'),
    ('Rahasia Dapur Restoran Jepang', 'Ternyata masakan Jepang punya teknik bumbu dan kualitas bahan tertentu agar rasanya otentik.', 'Food', 'Draft'),
    ('Cara Membuat API Gateway di Microservices', 'API gateway membantu komunikasi antar microservice, termasuk rate limit dan authentication.', 'Programming', 'Published'),
    ('Tren Fashion 2025', 'Tahun depan diprediksi muncul gaya minimalis, warna netral, dan bahan ramah lingkungan.', 'Lifestyle', 'Published'),
    ('Manfaat Berjemur di Pagi Hari', 'Sinar matahari membantu menghasilkan vitamin D dan meningkatkan mood.', 'Health', 'Published'),
    ('Belajar Dasar Git dan Version Control', 'Git adalah alat penting untuk kolaborasi developer. Artikel ini menjelaskan commit, push, pull, dan branching.', 'Programming', 'Published'),
    ('Kopi Literan Kekinian', 'Banyak kedai kopi kini menjual kopi literan dengan rasa bervariasi, cocok untuk kantor dan event.', 'Food', 'Published'),
    ('Cara Memilih Smartphone Terbaik', 'Pilih smartphone berdasarkan prosesor, RAM, kamera, serta baterai sesuai kebutuhan.', 'Technology', 'Published'),
    ('Wawancara Kerja yang Efektif', 'Tips menjawab pertanyaan HR, menggunakan bahasa tubuh yang benar, dan membuat kesan profesional.', 'Career', 'Draft'),
    ('Bahaya Konsumsi Gula Berlebihan', 'Gula berlebih menyebabkan obesitas dan diabetes. Kurangi minuman manis dan snack kemasan.', 'Health', 'Published'),
    ('Cara Membuat Blog WordPress dalam 30 Menit', 'WordPress memudahkan pemula membuat website tanpa coding. Artikel ini berisi langkah-langkahnya.', 'Technology', 'Published'),
    ('Resep Tahu Walik Crispy', 'Tahu walik adalah cemilan viral yang mudah dibuat. Cocok dinikmati dengan saus sambal.', 'Food', 'Published'),
    ('Pentingnya Backup Database', 'Backup mencegah kehilangan data akibat error atau serangan hacker.', 'Technology', 'Published'),
    ('Tips Lolos Seleksi Kampus Favorit', 'Persiapkan portofolio, nilai rapor, dan latihan soal sebelum ujian masuk.', 'Education', 'Published'),
    ('Cara Menurunkan Berat Badan Tanpa Diet Ketat', 'Cukup dengan olahraga ringan dan mengurangi porsi makan secara bertahap.', 'Health', 'Published'),
    ('Mengenal Kubernetes untuk Pemula', 'Kubernetes membantu mengatur container dalam skala besar. Banyak perusahaan sudah menggunakannya.', 'Programming', 'Draft'),
    ('Laptop Murah untuk Belajar Online', 'Rekomendasi laptop ringan dan hemat baterai untuk pelajar.', 'Technology', 'Published'),
    ('Pengalaman Pertama Naik Pesawat', 'Cerita lucu dan seru saat pertama kali terbang ke luar kota.', 'Travel', 'Published'),
    ('Apa Itu Cloud Computing?', 'Cloud memudahkan penyimpanan data tanpa harus membeli server sendiri.', 'Technology', 'Published'),
    ('Review Film Sci-Fi Terbaru', 'Film ini menghadirkan konsep perjalanan waktu dan visual yang keren.', 'Entertainment', 'Published'),
    ('Cara Mengatasi Anxiety Berlebihan', 'Teknik pernapasan, journaling, dan konsultasi profesional membantu mengatasi kecemasan.', 'Health', 'Published'),
    ('Investasi Emas untuk Pemula', 'Emas cocok untuk investasi jangka panjang karena nilai stabil.', 'Business', 'Published'),
    ('Tips Membuat CV Profesional', 'Gunakan template rapi, foto formal, dan highlight skill utama.', 'Career', 'Published');
